# Generated by Django 4.2.9 on 2024-02-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_email',
            new_name='user',
        ),
    ]
