# Generated by Django 4.2.9 on 2024-02-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_user_email_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
